GET https://localhost:5002/Repositories/repman
Accept: application/


###
POST https://localhost:5002/Repositories
Content-Type: application/json

{
  "name" : "repman"
}

###
PATCH https://localhost:5002/Repositories/repman
Content-Type: application/json

{
  "content" : "xxxx"
}
