GET https://localhost:5001/Packages/pac
Accept: application/json


###
POST https://localhost:5001/Packages
Content-Type: application/json

{
  "name" : "repman",
  "organization" : "maduProduction",
  "gitHubUrl" : "https://localhost:5002/Repositories/repman"
  
}


###
